---
# tasks file for Cluster_Config
- name: Copy /etc/hosts
  ansible.builtin.copy:
    src: hosts
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'

- name: Define the cluster/Add nodes to the cluster (Run on one node only)
  ansible.builtin.shell:
    cmd: |
       o2cb add-cluster ocfsCluster
       o2cb add-node ocfsCluster ol-sys0 --ip 192.168.1.5
       o2cb add-node ocfsCluster ol-sys1 --ip 192.168.1.20
       touch Adding_Nodes
  args:
    creates: Adding_Nodes
  when: ansible_host == 'ol-sys0'


# - name: Configure the global heartbeat mode but first make a ocfs on them (Run on one node only).
#   ansible.builtin.shell:
#     cmd: |
#        mkfs.ocfs2 -L ocfsghb /dev/sdc
#        o2cb add-heartbeat ocfsCluster /dev/sdc
#        o2cb heartbeat-mode ocfsCluster global
#        touch global_heartbeat
#   when: ansible_host == 'ol-sys0'



- name: copy file from machine1 to local
  fetch: 
    src: /etc/ocfs2/cluster.conf
    dest: /home/marwan/Desktop/Acpc-Ocfs/roles/Cluster_Config/files
  when: inventory_hostname == 'ol-sys0'
    

- name: copy file from local to machine2
  copy: 
    src: /home/marwan/Desktop/Acpc-Ocfs/roles/Cluster_Config/files/ol-sys0/etc/ocfs2/cluster.conf
    dest: /etc/ocfs2/cluster.conf
  when: inventory_hostname == 'ol-sys1'


- name: Preseed - Start OCFS2 cluster at boot time
  ansible.builtin.debconf:
    name: ocfs2-tools
    question: ocfs2-tools/start-o2cb
    value: true
    vtype: boolean

- name: Preseed - Cluster name to start at boot
  ansible.builtin.debconf:
    name: ocfs2-tools
    question: ocfs2-tools/cluster-name
    value: ocfsCluster
    vtype: string

- name: Preseed - O2CB heartbeat threshold
  ansible.builtin.debconf:
    name: ocfs2-tools
    question: ocfs2-tools/heartbeat-threshold
    value: 31       
    vtype: string

- name: Preseed - O2CB idle timeout
  ansible.builtin.debconf:
    name: ocfs2-tools
    question: ocfs2-tools/idle-timeout
    value: 30000
    vtype: string

- name: Preseed - O2CB keepalive delay
  ansible.builtin.debconf:
    name: ocfs2-tools
    question: ocfs2-tools/keepalive-delay
    value: 2000
    vtype: string

- name: Preseed - O2CB reconnect delay
  ansible.builtin.debconf:
    name: ocfs2-tools
    question: ocfs2-tools/reconnect-delay
    value: 2000
    vtype: string

- name: Run dpkg-reconfigure silently
  ansible.builtin.command: dpkg-reconfigure -f noninteractive ocfs2-tools

- name: Start and enabled o2cb
  ansible.builtin.service:
    name: o2cb
    enabled: yes
    state: restarted

- name: Enabled ocfs2
  ansible.builtin.service:
    name: ocfs2
    enabled: yes

- name: Configure the sysctlkernel parameters.
  ansible.builtin.copy:
    src: 99-sysctl.conf
    dest: /etc/sysctl.d/99-sysctl.conf
    owner: root
    group: root
    mode: '0644'


- name: Configure the sysctlkernel.
  ansible.builtin.shell:
    cmd: |
       sysctl -p
  


- name: Create an OCFS2 volume for the data block storage.
  ansible.builtin.shell:
    cmd: |
       mkfs.ocfs2 -N 4 -L "myvol" /dev/sdb && touch ocfs2device
  args:
    creates: ocfs2device
  when: ansible_host == 'ol-sys0'

- name: register-cluster ocfsCluster.
  ansible.builtin.shell:
    cmd: |
       sudo o2cb register-cluster ocfsCluster


- name:  Create a mount point.
  ansible.builtin.shell:
    cmd: |
       mkdir "{{Mount_PointBath}}"
       touch Mount-Point_Created
       mount -L myvol "{{Mount_PointBath}}"
  args:
    creates: Mount-Point_Created
  when: ansible_host == 'ol-sys0'



- name:  Create a mount point.
  ansible.builtin.shell:
    cmd: |
       sudo o2cb register-cluster ocfsCluster
       mkdir "{{Mount_PointBath}}"
       touch Mount-Point_Created
       mount -L myvol "{{Mount_PointBath}}"
  args:
    creates: Mount-Point_Created
  when: ansible_host == 'ol-sys1'